[files]
extend-exclude = ["loadtest", "doc/**/mermaid.*js", "doc/html/**/*"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[default.extend-identifiers]

[default.extend-words]
ro = "ro"
ratatui = "ratatui"
wrk = "wrk"

[type.rust]
extend-glob = []
extend-ignore-identifiers-re = []
extend-ignore-words-re = ["udid", "typ"]
extend-ignore-re = [
  "gAA.*\\b"
]

[type.rust.extend-identifiers]
flate2 = "flate2"
wher = "wher"

[type.rust.extend-words]
ro = "ro"
ser = "ser"
COSE = "COSE"

[type.lock]
extend-glob = []
check-file = false
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []

[type.lock.extend-identifiers]

[type.lock.extend-words]

[type.js]

[type.md]
extend-ignore-identifiers-re = ["HashiCorp"] 
